name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  water:
    path: ../packages/water
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_modular: ^6.3.3
  equatable: ^2.0.5
  wear_plus: ^1.2.0
  iconly: ^1.0.1
  rotary_scrollbar: ^0.1.1
  is_wear: ^0.0.1+2
  device_info: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/waves.json